### ISSUE TITLE
Replace GET calls from Algod to Indexer calls

### ISSUE THREAD

**Issue by johnclarke96** [Algofiorg/algofi-py-sdk#32]

**Comment by guanzo** [comment]
I think you already implemented this but was pondering the feasability of supporting both algod and indexer clients where applicable. Hosting a non archival node is relatively cheap, while hosting a indexer + archival node is expensive. If I could send requests to my hosted algod where possible and the rest to public indexers, that'd be ideal. 

Is this something you'd consider or accept a PR for?

**Comment by johnclarke96** [comment]
How would you implement? I suppose you could use a boolean wherever necessary to say, use_algod. Indexer should be the default imo as it is more efficient for querying data.

**Comment by guanzo** [comment]
I agree indexer should be the default. Also algoexplorer algod nodes don't support GET calls anymore, so this proposal is moreso for people with self hosted algod nodes.

I would create a class that wraps the algod and indexer clients and accepts a bool to determine which client to use.

> How would you implement?

Something like this

```py
class ApiClient:
    def __init__(self, indexer_client, algod_client, use_indexer=True):
        self.indexer = indexer_client
        self.algod = algod_client
        self.use_indexer = use_indexer

    def account_info (self, address):
        if self.use_indexer:
            account_info = self.indexer.account_info(address).get("account", {})
        else:
            account_info = self.algod.account_info(address)

        return account_info

    def application_info (self, app_id):
        if self.use_indexer:
            app_info = self.indexer.applications(app_id).get("application", {})
        else:
            app_info = self.algod.application_info(app_id)

        return app_info

    def asset_info (self, asset_id):
        if self.use_indexer:
            asset_info = self.indexer.asset_info(asset_id).get("asset",{})['params']
        else:
            asset_info = self.algod.asset_info(asset_id)["params"]

        return asset_info
```

`use_indexer` would need to be passed to the `AlgofiMainnetClient`

Then for the applicable requests, anywhere you used to pass in algod or indexer, you'd pass this wrapped client instead.

Example:

```py
def read_local_state(api_client, address, app_id, block=None):
    try:
        results = api_client.account_info(address)
    except:
        raise Exception("Account does not exist.")

    for local_state in results['apps-local-state']:
        if local_state['id'] == app_id:
            if 'key-value' not in local_state:
                return {}
            return format_state(local_state['key-value'])
    return {}
```

**Comment by johnclarke96** [comment]
Interesting. Would you instantiate this api_client within the Client class?

**Comment by guanzo** [comment]
Yep! I'd update the constructor like so. https://github.com/Algofiorg/algofi-py-sdk/blob/4c23e6064a0f33ccb538421f2c6db412d3d4e9ea/algofi/v1/client.py#L39-L63

```diff
class Client:
    def __init__(self, algod_client: AlgodClient, indexer_client: IndexerClient, historical_indexer_client: IndexerClient,
                 user_address, chain, use_indexer=True):
-      self.algod = algod_client
-      self.indexer = indexer_client
+      self.api_client = new ApiClient(indexer_client, algod_client, use_indexer)
```

**Comment by johnclarke96** [comment]
Ok, cool. Perhaps you can create the ApiClient class and implement this in 1 function to show as an example. Following our review, you can proceed with implementing throughout the sdk? Thanks for the work btw!

**Comment by guanzo** [comment]
https://github.com/Algofiorg/algofi-py-sdk/pull/39

**Comment by guanzo** [comment]
It's much simpler to just subclass the Indexer and override the appropriate methods. I'll go with this for now.

```py
class AlgodIndexerCombo(IndexerClient):
    def __init__(self, algod, indexer_token, indexer_address, headers=None):
        super().__init__(indexer_token, indexer_address, headers)
        self.algod = algod

    def account_info (self, address, round_num=None):
        account_info = self.algod.account_info(address)
        return { 'account': account_info }

    def applications (self, app_id, round_num=None):
        app_info = self.algod.application_info(app_id)
        return { 'application': app_info }

    def asset_info (self, asset_id):
        asset_info = self.algod.asset_info(asset_id)
        return { 'asset': asset_info }


algod= AlgodClient(API_TOKEN, ALGO_NODE_ORIGIN)
indexer = AlgodIndexerCombo(algod, "", "https://algoindexer.algoexplorerapi.io")
client =  AlgofiMainnetClient(indexer=indexer)
 ```

**Comment by johnclarke96** [comment]
I'll review this soon. Thanks!

**Comment by johnclarke96** [comment]
Hey, I wonder if the naming scheme would be a bit confusing here. I think your other PR with the ApiClient was clean.

**Comment by guanzo** [comment]
The `AlgodIndexerCombo` can be created in userland and passed to the `AlgofiMainnetClient`, meaning the sdk doesn't need to be updated at all. It's a lot less work - albeit a bit hacky - to achieve the same effect, that's why I prefer it. No PR necessary.

Also I'd find it weird if the python sdk had this `ApiClient` and the js sdk didn't.

**Comment by johnclarke96** [comment]
Fair play -- this is easier to deploy. Thanks for investigating this.
