### ISSUE TITLE
'get_storage_state' is not defined

### ISSUE THREAD

**Issue by Alec-Schneider** [Algofiorg/algofi-py-sdk#5]
Hi,

In the algofi/v1/manager module the get_user_state function of the Manager class returns the get_storage_state function, however it needs to be calling self.get_storage_state. Please let me know if you would like me to contribute the fix! Error message below

####################################
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-12-ea491a5dd131> in <module>
      6 print("~"*100)
      7 print_market_state(client.get_market(symbol))
----> 8 print_user_state(client, symbol, sender)

~/algorand/algofi-py-sdk/examples/example_utils.py in print_user_state(client, symbol, address)
     12 
     13 def print_user_state(client, symbol, address):
---> 14     user_state = client.get_user_state(address)
     15     for key, value in user_state["manager"].items():
     16         print(key, "=", value)

~/.local/lib/python3.8/site-packages/algofi/v1/client.py in get_user_state(self, address)
    169         if not address:
    170             address = self.user_address
--> 171         result["manager"] = self.manager.get_user_state(address)
    172         storage_address = self.manager.get_storage_address(address)
    173         for symbol in self.active_ordered_symbols:

~/.local/lib/python3.8/site-packages/algofi/v1/manager.py in get_user_state(self, address)
     93         result = {}
     94         storage_address = self.get_storage_address(address)
---> 95         return get_storage_state(storage_address)
     96 
     97     def get_storage_state(self, storage_address):

NameError: name 'get_storage_state' is not defined

**Comment by Alec-Schneider** [comment]
Pull request link below:
https://github.com/Algofiorg/algofi-py-sdk/pull/6

**Comment by maks-ivanov** [comment]
Thanks, good catch
