### ISSUE TITLE
fix examples/example_utils.py/print_user_state

### ISSUE THREAD

**Issue by Alec-Schneider** [Algofiorg/algofi-py-sdk#8]
In the print_user_state function of the exampl_utils module the function is trying to get asset information from a market object. Suggestion is to get the asset object from the market object before printing out the information.

**Comment by Alec-Schneider** [comment]
PR link: https://github.com/Algofiorg/algofi-py-sdk/pull/9

**Comment by johnclarke96** [comment]
Merged previously. Thanks!
